import os
import random
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

load_dotenv()

usuario = os.getenv("DB_USER") or os.getenv("ORACLE_USER")
senha = os.getenv("DB_PASS") or os.getenv("ORACLE_PASSWORD")
host = os.getenv("DB_HOST") or os.getenv("ORACLE_HOST")
porta = os.getenv("DB_PORT") or os.getenv("ORACLE_PORT")
servico = os.getenv("DB_SERVICE") or os.getenv("ORACLE_SERVICE_NAME")

url_banco = f"oracle+oracledb://{usuario}:{senha}@{host}:{porta}/?service_name={servico}"

print("Conectando ao banco Oracle da FIAP...")
engine = create_engine(url_banco)

create_table_sql = """
CREATE TABLE SENSORES (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UMIDADE_SOLO NUMBER,
    PH NUMBER,
    NITROGENIO NUMBER,
    FOSFORO NUMBER,
    POTASSIO NUMBER,
    VAI_CHOVER NUMBER(1),
    BOMBA_LIGADA NUMBER
)
"""

insert_sql = """
INSERT INTO SENSORES (UMIDADE_SOLO, PH, NITROGENIO, FOSFORO, POTASSIO, VAI_CHOVER, BOMBA_LIGADA)
VALUES (:umidade_solo, :ph, :nitrogenio, :fosforo, :potassio, :vai_chover, :bomba_ligada)
"""

try:
    with engine.begin() as conn:
        # Check if table exists
        try:
            conn.execute(text('SELECT 1 FROM "SENSORES" WHERE ROWNUM = 1'))
            print("A tabela 'SENSORES' já existe no banco Oracle.")
        except Exception:
            print("Tabela 'SENSORES' não encontrada. Criando a tabela...")
            conn.execute(text(create_table_sql))
            print("Tabela 'SENSORES' criada com sucesso.")

        # Check number of rows
        res = conn.execute(text('SELECT COUNT(*) FROM "SENSORES"'))
        row_count = res.scalar()
        print(f"Total de registros atuais: {row_count}")

        if row_count < 100:
            print(f"Inserindo dados simulados para treinamento (faltam {100 - row_count} registros)...")
            for _ in range(100 - row_count):
                umidade = round(random.uniform(20.0, 80.0), 2)
                ph = round(random.uniform(5.0, 7.5), 2)
                n = round(random.uniform(10, 50), 2)
                p = round(random.uniform(10, 50), 2)
                k = round(random.uniform(10, 50), 2)
                vai_chover = random.choice([0, 1])
                tempo_bomba = 0
                if umidade < 40 and vai_chover == 0:
                    tempo_bomba = round((40 - umidade) * 1.5, 2)
                
                conn.execute(text(insert_sql), {
                    "umidade_solo": umidade,
                    "ph": ph,
                    "nitrogenio": n,
                    "fosforo": p,
                    "potassio": k,
                    "vai_chover": vai_chover,
                    "bomba_ligada": tempo_bomba
                })
            print("Dados simulados inseridos com sucesso!")
except Exception as e:
    print(f"Erro geral: {e}")
